# Dockerfile.ollama
FROM ollama/ollama:latest

# Устанавливаем curl для проверок
RUN apt-get update && apt-get install -y curl

# Создаем entrypoint скрипт
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

EXPOSE 11434
#точку входа
ENTRYPOINT ["/entrypoint.sh"]
